[package]
name = "aoc2023-17-1"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
indoc = { workspace = true }
tracing-test = { workspace = true }
