[package]
name = "aoc2023-08-2"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = { workspace = true }
rayon = { workspace = true }
regex = { workspace = true }

[dev-dependencies]
indoc = { workspace = true }
