[package]
name = "aoc2023-18-2"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools.workspace = true
nom = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
indoc = { workspace = true }
